[package]
name = "tpx-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tpx-core = { path = "../tpx-core" }
tpx-runtime = { path = "../tpx-runtime" }
runtime-local = { path = "../runtimes/runtime-local" }
runtime-script = { path = "../runtimes/runtime-script" }
runtime-oci = { path = "../runtimes/runtime-oci" }
